# Generated by Django 5.1.5 on 2025-01-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0002_alter_imagen_footer_alter_imagen_logo_grande_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagen",
            name="footer",
            field=models.ImageField(blank=True, null=True, upload_to="footer"),
        ),
        migrations.AlterField(
            model_name="imagen",
            name="logo_grande",
            field=models.ImageField(blank=True, null=True, upload_to="large"),
        ),
        migrations.AlterField(
            model_name="imagen",
            name="logo_pequeño",
            field=models.ImageField(blank=True, null=True, upload_to="small"),
        ),
        migrations.AlterField(
            model_name="imagen",
            name="logo_ticket",
            field=models.ImageField(blank=True, null=True, upload_to="ticket"),
        ),
        migrations.AlterField(
            model_name="imagen",
            name="wallpaper_turnero",
            field=models.ImageField(blank=True, null=True, upload_to="wallpaper"),
        ),
    ]
