# Generated by Django 5.1.5 on 2025-01-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turnos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="turnero",
            name="menus",
            field=models.ManyToManyField(related_name="turneros", to="turnos.menu"),
        ),
    ]
