# Generated by Django 5.1.5 on 2025-01-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turnos", "0003_menu_descripcion_turnero_ubicacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sala",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
