# Generated by Django 5.1.5 on 2025-01-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Espera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etiquetas_llamado_individual_multiple",
                    models.TextField(
                        blank=True,
                        default="{turno}: Número de turno completo.\n        {turno_dividido}: Número de turno deletreado.\n        {cedula}: Número de cédula completa (En caso de que la cédula haya sido ingresada).\n        {cliente_nombre}: Nombre cliente (En caso de que al momento de llamar el turno el cliente haya ingresado su cédula).\n        {cliente_apellido}: Apellido Cliente (En caso de que al momento de llamar el turno el cliente haya ingresado su cédula).\n        {cedula_dividido}:Número de cédula deletreada (En caso de que la cédula haya sido ingresada).\n        {cedula_existe_inicio} {cedula_existe_cierre}: Mensaje condicional (En caso de que la cédula haya sido ingresada).\n        {turno}: Número de turno entero.\n        {ventanilla}: Nombre de la ventanilla.",
                        null=True,
                    ),
                ),
                (
                    "llamado_sala_espera_individual",
                    models.CharField(
                        blank=True,
                        default="@ turno. {turno_dividido} {cedula_existe_inicio} con documento {cedula_existe_cierre} {cedula} pase a. {ventanilla}",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "llamado_sala_espera_multiple_parte1",
                    models.CharField(
                        blank=True, default="@ Turnos.", max_length=300, null=True
                    ),
                ),
                (
                    "llamado_sala_espera_multiple_parte2",
                    models.CharField(
                        blank=True,
                        default="@ {turno_dividido}",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "llamado_sala_espera_multiple_parte3",
                    models.CharField(
                        blank=True,
                        default="@ pasen a. {ventanilla}",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "titulo_columna_turnos",
                    models.CharField(
                        blank=True, default="TURNO", max_length=50, null=True
                    ),
                ),
                (
                    "titulo_columna_espera",
                    models.CharField(
                        blank=True, default="ESPERA TR", max_length=50, null=True
                    ),
                ),
                (
                    "titulo_columna_ventanillas",
                    models.CharField(
                        blank=True, default="SERVICIO", max_length=50, null=True
                    ),
                ),
                (
                    "limite_turnos_visibles_presentacion",
                    models.IntegerField(blank=True, default=7, null=True),
                ),
            ],
        ),
    ]
