# Generated by Django 5.1.5 on 2025-01-25 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espera", "0001_initial"),
        ("turnos", "0004_sala_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColaEspera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_turnos", models.IntegerField(default=10)),
                (
                    "ordenar_por",
                    models.CharField(
                        choices=[
                            ("tiempo", "Tiempo de Espera"),
                            ("prioridad", "Prioridad"),
                        ],
                        default="tiempo",
                        max_length=20,
                    ),
                ),
                ("mostrar_atendidos", models.BooleanField(default=True)),
                ("mostrar_anulados", models.BooleanField(default=False)),
                (
                    "limite_turnos_visibles_presentacion",
                    models.IntegerField(blank=True, default=7, null=True),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colas",
                        to="turnos.sala",
                    ),
                ),
            ],
        ),
    ]
