# Generated by Django 5.1.5 on 2025-01-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagen",
            name="footer",
            field=models.ImageField(blank=True, null=True, upload_to="images/footer"),
        ),
        migrations.AlterField(
            model_name="imagen",
            name="logo_grande",
            field=models.ImageField(blank=True, null=True, upload_to="images/large"),
        ),
        migrations.AlterField(
            model_name="imagen",
            name="logo_pequeño",
            field=models.ImageField(blank=True, null=True, upload_to="images/small"),
        ),
        migrations.AlterField(
            model_name="imagen",
            name="logo_ticket",
            field=models.ImageField(blank=True, null=True, upload_to="images/ticket"),
        ),
        migrations.AlterField(
            model_name="imagen",
            name="wallpaper_turnero",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/wallpaper"
            ),
        ),
    ]
