# Generated by Django 5.1.5 on 2025-01-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0003_alter_imagen_footer_alter_imagen_logo_grande_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sistema",
            name="email_notificaciones",
            field=models.EmailField(
                blank=True,
                default="pipebustamante@gmail.com",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sistema",
            name="enlace_encuesta",
            field=models.URLField(
                blank=True,
                default="http://turnosmart.com/digiturnos/encuesta.php",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sistema",
            name="enlace_recuperacion_clave",
            field=models.URLField(
                blank=True,
                default="http://turnosmart.com/digiturnos/recuperarclave.php",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sistema",
            name="remitente_notificaciones",
            field=models.CharField(
                blank=True, default="TurnoSmart", max_length=200, null=True
            ),
        ),
    ]
