# Generated by Django 5.1.5 on 2025-01-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0004_alter_sistema_email_notificaciones_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sistema",
            name="copyright",
            field=models.CharField(default="Juan Felipe Bustamante", max_length=200),
        ),
    ]
