# Generated by Django 5.1.5 on 2025-01-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turnos", "0002_turnero_menus"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="turnero",
            name="ubicacion",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="turnero",
            name="menus",
            field=models.ManyToManyField(
                blank=True, related_name="turneros", to="turnos.menu"
            ),
        ),
    ]
