# Generated by Django 5.1.5 on 2025-01-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timbre",
                    models.FileField(blank=True, null=True, upload_to="audios/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Imagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo_pequeño",
                    models.ImageField(blank=True, null=True, upload_to="small"),
                ),
                (
                    "logo_grande",
                    models.ImageField(blank=True, null=True, upload_to="large"),
                ),
                (
                    "logo_ticket",
                    models.ImageField(blank=True, null=True, upload_to="ticket"),
                ),
                (
                    "footer",
                    models.ImageField(blank=True, null=True, upload_to="footer"),
                ),
                (
                    "wallpaper_turnero",
                    models.ImageField(blank=True, null=True, upload_to="wallpaper"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Institucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("siglas", models.CharField(blank=True, max_length=20, null=True)),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
                ("ubicacion", models.CharField(blank=True, max_length=200, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("sitio_web", models.URLField(blank=True, null=True)),
                ("mensaje", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tiempo_espera", models.IntegerField(default=10)),
                ("umbral_espera", models.IntegerField(default=5)),
                ("mostrar_turnos_anulados", models.BooleanField(default=False)),
                ("mostrar_turnos_atendidos", models.BooleanField(default=False)),
                ("num_max_turnos_cedula", models.IntegerField(default=1)),
                ("digitos_max_cedula_turnero", models.IntegerField(default=15)),
                ("enviar_encuesta_cliente", models.BooleanField(default=False)),
                ("asignacion_automatica", models.BooleanField(default=False)),
                ("version_sistema", models.CharField(default="4.0.1", max_length=20)),
                (
                    "copyright",
                    models.CharField(default="Juan Felipe Bustamante", max_length=200),
                ),
                (
                    "contrasena_email_notificaciones",
                    models.CharField(
                        blank=True, default="a", max_length=200, null=True
                    ),
                ),
                (
                    "puerto_notificaciones",
                    models.IntegerField(blank=True, default=587, null=True),
                ),
                ("duracion_link_recuperacion_clave", models.IntegerField(default=1)),
                (
                    "mostrar_turnos_llamados_sin_atender",
                    models.BooleanField(default=True),
                ),
                (
                    "solicitar_confirmacion_obtener_turnos",
                    models.BooleanField(default=False),
                ),
                ("abrir_encuesta_atencion", models.BooleanField(default=False)),
                (
                    "emision_ticket",
                    models.CharField(
                        choices=[("IMPRIMIR", "Imprimir"), ("QR", "QR")],
                        default="IMPRIMIR",
                        max_length=20,
                    ),
                ),
                (
                    "url_copyright",
                    models.URLField(blank=True, default="https://piisa.com", null=True),
                ),
                (
                    "email_notificaciones",
                    models.EmailField(
                        blank=True,
                        default="pipebustamante@gmail.com",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "host_notificaciones",
                    models.CharField(
                        blank=True, default="smtp.gmail.com", max_length=200, null=True
                    ),
                ),
                (
                    "remitente_notificaciones",
                    models.CharField(
                        blank=True, default="TurnoSmart", max_length=200, null=True
                    ),
                ),
                (
                    "enlace_recuperacion_clave",
                    models.URLField(
                        blank=True,
                        default="http://turnosmart.com/digiturnos/recuperarclave.php",
                        null=True,
                    ),
                ),
                (
                    "enlace_encuesta",
                    models.URLField(
                        blank=True,
                        default="http://turnosmart.com/digiturnos/encuesta.php",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ancho_ticket", models.IntegerField(default=80)),
                ("ancho_logo", models.IntegerField(default=35)),
                ("alto_logo", models.IntegerField(default=38)),
                ("logo_visible", models.BooleanField(default=True)),
                ("fuente_turno", models.IntegerField(default=14)),
                ("fuente_tramite", models.IntegerField(default=5)),
                ("tramite_visible", models.BooleanField(default=True)),
                ("fuente_prioridad", models.IntegerField(default=3)),
                ("prioridad_visible", models.BooleanField(default=True)),
                ("fuente_nombre", models.IntegerField(default=2)),
                ("nombre_visible", models.BooleanField(default=True)),
                ("fuente_espera", models.IntegerField(default=3)),
                ("espera_visible", models.BooleanField(default=True)),
                ("fuente_hora", models.IntegerField(default=2)),
                ("hora_visible", models.BooleanField(default=True)),
                ("fuente_fecha", models.IntegerField(default=2)),
                ("fecha_visible", models.BooleanField(default=True)),
                ("fuente_sitio_web", models.IntegerField(default=1)),
                ("sitio_web_visible", models.BooleanField(default=True)),
                ("fuente_nombre_cliente", models.IntegerField(default=3)),
                ("nombre_cliente_visible", models.BooleanField(default=True)),
                ("fuente_cedula_cliente", models.IntegerField(default=3)),
                ("cedula_cliente_visible", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("URL", "URL Externa"),
                            ("SISTEMA", "Videos subidos en el sistema"),
                        ],
                        default="URL",
                        max_length=20,
                    ),
                ),
                ("url_video", models.URLField(blank=True, null=True)),
                ("video", models.FileField(blank=True, null=True, upload_to="videos/")),
                ("estado", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Voz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("llamado_turno_con_voz", models.BooleanField(default=True)),
                (
                    "origen_voz",
                    models.CharField(
                        choices=[
                            ("TTS NAVEGADOR WEB", "TTS NAVEGADOR WEB"),
                            ("URL EXTERNA", "URL Externa"),
                        ],
                        default="TTS NAVEGADOR WEB",
                        max_length=20,
                    ),
                ),
                (
                    "idioma",
                    models.CharField(default="ESPAÑOL (ESPAÑA)", max_length=200),
                ),
                ("tono", models.FloatField(default=1.0)),
                ("velocidad", models.FloatField(default=1.0)),
                ("volumen", models.FloatField(default=1.0)),
            ],
        ),
    ]
