# Generated by Django 5.1.5 on 2025-02-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0002_ticket_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="nombre",
            field=models.CharField(default="Sin nombre", max_length=255),
        ),
        migrations.AlterField(
            model_name="sistema",
            name="version_sistema",
            field=models.CharField(default="1.0.0", max_length=20),
        ),
    ]
