# Generated by Django 5.1.5 on 2025-02-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0003_video_nombre_alter_sistema_version_sistema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="nombre",
            field=models.CharField(default="Default", max_length=255),
        ),
    ]
