# Generated by Django 5.1.5 on 2025-02-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0004_alter_video_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="nombre",
            field=models.CharField(max_length=255),
        ),
    ]
