# Generated by Django 5.1.5 on 2025-01-26 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FranjaHoraria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("estado", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prioridad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("ALTA", "ALTA"),
                            ("MEDIA", "MEDIA"),
                            ("BAJA", "BAJA"),
                            ("MUY ALTA", "MUY ALTA"),
                        ],
                        default="MEDIA",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lunes", models.BooleanField(default=False)),
                ("martes", models.BooleanField(default=False)),
                ("miercoles", models.BooleanField(default=False)),
                ("jueves", models.BooleanField(default=False)),
                ("viernes", models.BooleanField(default=False)),
                ("sabado", models.BooleanField(default=False)),
                ("domingo", models.BooleanField(default=False)),
                (
                    "franja_horaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="turnos.franjahoraria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CONTENEDOR", "Menú Contenedor"),
                            ("TRAMITE", "Trámite"),
                        ],
                        max_length=100,
                    ),
                ),
                ("horario_general", models.BooleanField(default=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="menu_icons/"),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tramite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.tramite",
                    ),
                ),
                (
                    "prioridad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="turnos.prioridad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tramite_turnos_en_espera",
                    models.ManyToManyField(
                        related_name="salas_espera", to="core.tramite"
                    ),
                ),
                (
                    "ventanillas_asignadas",
                    models.ManyToManyField(
                        related_name="salas_atencion", to="core.ventanilla"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Turnero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("ubicacion", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "presentacion",
                    models.CharField(
                        choices=[("IMPRIMIR", "Imprimir"), ("QR", "QR")],
                        default="IMPRIMIR",
                        max_length=10,
                    ),
                ),
                (
                    "menus",
                    models.ManyToManyField(
                        blank=True, related_name="turneros", to="turnos.menu"
                    ),
                ),
            ],
        ),
    ]
