# Generated by Django 5.1.5 on 2025-02-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turnos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="menus/"),
        ),
    ]
