name: Run Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install Dependencies
        run: |
          cd backend
          python3 -m venv venv
          source venv/bin/activate
          pip install -r /home/runner/work/turnosmart/turnosmart/backend/requirements.txt # Ruta completa a requirements.txt

      - name: Run Django Tests
        run: |
          source backend/venv/bin/activate # Ahora sin cd
          python manage.py test core