name: Run Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install Dependencies
        run: |
          cd frontend  # Cambia al directorio correcto
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Tests
        run: |
          cd frontend  # Asegurarse de estar en el directorio correcto
          source venv/bin/activate
          python manage.py test apps
